language: node_js
node_js:
  - '11'
install:
  - cd tasks
  - yarn install
  - cd ../models
  - yarn install
  - cd ../backend
  - yarn install
  - cd ../frontend
  - yarn install
  - cd ..
script:
  - cd models
  - yarn run lint
  - cd ../tasks
  - yarn run lint
  - gulp models
  - cd ../backend
  - yarn run ci:build
  - yarn run lint
  - yarn test
  - cd ../frontend
  - yarn build
  - yarn run lint
  - yarn test
